### ISSUE TITLE
Not seeing "server.js" file after accepting the assignment.

### ISSUE THREAD

**Issue by jykim111** [comp426-2022-spring/a01#1]
I was able to accept the a01 assignment and cloned the repository through the Github classroom link, but for some reason, I do not see the "server.js" file in the repository.
Is there something wrong on my end?

**Comment by camsimba** [comment]
Hey @jykim111, I believe the intended file is 'server.js.example' in the repository code. There seems to be a discrepancy between the repository and write-up. You can use this file in the meantime to write your server code, though we may end up changing the name for clarity. Let me know if you don't see 'server.js.example'.

**Comment by kelseyfaunt** [comment]
I'm having the same issue as well. Is it okay to just add the file myself or should I take a different approach?

**Comment by jdmar3** [comment]
I've updated the instructions to include a note about `server.js.example` and needing to copy or rename it to `server.js`
