### ISSUE TITLE
 Autgroader issue: ❌ Run server listening on randomly-assigned port

### ISSUE THREAD

**Issue by largeweb** [comp426-2022-spring/a01#10]
After following the walkthrough in class and successfully getting my server to work, I keep running into this issue with the autograder. Reading through the regex, I think there may be a possible syntax error? I'm not sure if it is on my end or the autograder.

Autograder full message:
```
 ❌ Run server listening on randomly-assigned port
::error::The output for test Run server listening on randomly-assigned port did not match%0AExpected:%0A[Pp]ort(\s|\S)([0-9]{4,5})\nHTTP\/(1.1|2) 200(\sOK)?\nContent-Type: text\/html%0AActual:%0AServer is running on port: 65305%0AHTTP/1.1 200 OK%0AContent-Type: text/html%0ADate: Thu, 27 Jan 2022 21:34:20 GMT%0AConnection: keep-alive%0AKeep-Alive: timeout=5
📝 Status code


  Server is running on port: 18436
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  HTTP/1.1 200 OK
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  Content-Type: text/html
  Date: Thu, 27 Jan 2022 21:34:26 GMT
  Connection: keep-alive
  Keep-Alive: timeout=5
```
Here is my exact console.log line:
console.log(`Server is running on port: ${port}`);

**Comment by ravent61** [comment]
I'm having this same issue

**Comment by camsimba** [comment]
Hey @largeweb, sorry about not seeing this until now. The error is stating that the output string you made is wrong, it expected something different. It looks like on line 44 of your code, you add an extra colon to the string after port, the string should be exactly as written in the comments of `server.js`. Try taking that out and running it again, I think it should work afterwards. If not, just let me know and we can work on it some more!

**Comment by largeweb** [comment]
Thank you camsimba, this was my issue, I used "running" instead of "listening" and added a colon when I shouldn't've.

**Comment by camsimba** [comment]
Sounds good, glad I could help!
