### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by bvalient** [comp426-2022-spring/a01#13]
Hi, I am currently getting this error (as seen in pictures) I looked it up on google to no really clear way of fixing this. Any help would be great.

<img width="649" alt="Screen Shot 2022-01-31 at 11 19 47 PM" src="https://user-images.githubusercontent.com/69774341/151912269-bb330d3b-0360-4bbc-9d39-6c13765d9493.png">

**Comment by camsimba** [comment]
Hi, I just want to make sure of something that might be the issue. Did you rename the `server.js.example` to `server.js`? The error you are getting is that the command cannot find a file named 'server.js', which can mean that either the file is named incorrectly in your directory, the file is not there, or you are in the wrong directory (i.e. maybe you need to execute the command not in `/Users/bvalient/Comp426-WorkSpace/` but in `/Users/bvalient/Comp426-WorkSpace/a01` if you have your a01 code in that directory). 

If you named the file correctly, type `ls` in your command line and post a screenshot of it, it should help give some more information of what is contained in your working directory for me. Let me know if any of this helped!

**Comment by bvalient** [comment]
Here is the ls command

<img width="349" alt="Screen Shot 2022-02-03 at 10 48 05 PM" src="https://user-images.githubusercontent.com/69774341/152468690-84b33c94-3f20-496b-a81e-fc6c61e1ae8f.png">

**Comment by bvalient** [comment]
More detailed ls

<img width="635" alt="Screen Shot 2022-02-03 at 11 04 13 PM" src="https://user-images.githubusercontent.com/69774341/152469949-85d51572-9015-4fc6-94c2-edbfb7d67e5f.png">

**Comment by bvalient** [comment]
You were right about needed to execute in the a01 directory! Thank you!

**Comment by camsimba** [comment]
All good, glad I could help!
