### ISSUE TITLE
Trouble pushing code to GitHub

### ISSUE THREAD

**Issue by mkrishn852** [comp426-2022-spring/a01#15]
I've tried recloning my code to push it to GitHub, but it keeps giving me a "fatal" message. I also tried pushing from my VS Code GUI and terminal.

**Comment by samrshi** [comment]
Problem was resolved after pulling from GitHub repo before pushing. However, I think that something else you had tried before coming to office hours had helped the situation. Because pulling first would not solve previous error message about password auth deprecation.
