### ISSUE TITLE
Passing all tests except for table?

### ISSUE THREAD

**Issue by jenlevy** [comp426-2022-spring/a01#16]
Hello! I'm having an issue figuring out what I'm doing wrong in terms of my table and index.html - whenever I push autograder says output for the test table is different than excepted and I'm only failing table check. I am also having issues with running browser sync - it works when I run it for a00 but when i try to run it for this assignment to see the table I get an error on my local host saying "cannot /GET"

**Comment by jdmar3** [comment]
Ah I see the issue. The reason that your table is not passing the check is that you haven't finished building the table out fully. If you build it out so that it contains the whole alphabet, you should be all set!
